apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: frontend-deployment
          image: berlinbenilo2105/medgptfrontend:v1
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://20.41.250.191:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-deployment
  ports:
    - port: 80
      targetPort: 80
